### ISSUE TITLE
How can I get the number of results when doing a client-side search 

### ISSUE THREAD

**Issue by Philippe-Chevalier** [lorenzofox3/Smart-Table#278] opened 2015-01-14 18:29 UTC
hello,
I would like to display the number of results when i do a search from the client side  using an input with st-search.
$scope.displayedCollection.length will not give the right answer if I use pagination and have more than one page of results...

**Comment by lorenzofox3** [comment] 2015-01-14 19:41
Hi, 
you can't, the filtered collection is an internal variable. You'll need to expose it see [here](https://github.com/lorenzofox3/Smart-Table/blob/master/src/stTable.js#L87)

**Comment by Philippe-Chevalier** [comment] 2015-01-15 09:24
Hi,
Thanks for your quick reply and for this plugin :) For far, the best I found to simply display tables with angularJS. Could you consider adding the filtered.length information to tableState in a furure version ? I think it's a usefull information to display to the user...

**Comment by lorenzofox3** [comment] 2015-01-18 10:35
duplicate of #261

**Closed by lorenzofox3** 2015-01-18 10:35 UTC
