### ISSUE TITLE
Select row plugin not work with ajax

### ISSUE THREAD

**Issue by Alvise88** [lorenzofox3/Smart-Table#395] opened 2015-05-06 16:49 UTC
There is a problem with safeCopy. When table controller is starting the var safeCopy is not properly setted. The solution is that:

Add to the stTableController this code:

 this.safeCopy = function(){
      copyRefs(displayGetter($scope));
 };

And the post link of pipe directive must become:

post: function (scope, element, attrs, ctrl) {
          ctrl.pipe();
          ctrl.safeCopy(); //The function added before
}

Otherwise the function "function select (row, mode)" will see var rows void.

**Comment by Alvise88** [comment] 2015-05-06 17:20
The issue was not resolved by previous message due the asynchronous nature of pipe.

with the following piece of code at the end of stTableController  i have resolved my problem:

$scope.$watch($attrs.stTable, function() {
       safeCopy = copyRefs(displayGetter($scope));
});

**Comment by pacior** [comment] 2015-05-07 16:50
This solution worked also for me.

**Comment by lorenzofox3** [comment] 2015-05-10 07:47
duplicate of #390

**Closed by lorenzofox3** 2015-05-10 07:47 UTC
