### ISSUE TITLE
Selecting filtered data with pagination

### ISSUE THREAD

**Issue by rntorm** [lorenzofox3/Smart-Table#295] opened 2015-02-08 14:58 UTC
First of all, thank you for this beautiful plugin! 

I have one issue though: 

I created checkbox directive for selecting row. When I filter data and result is multiple pages long, selection does not work with st-safe-src="rowCollection". Selected data is always the whole dataset, not filtered rows. On the other hand if I select the st-table="copiedCollection", only the visible page is selected. 

Is there any way to select only the filtered data?

**Comment by lorenzofox3** [comment] 2015-02-23 05:16
there is at the moment no way to access the filtered data. You will only be able to access the displayed collection ie the result of sort, filter and *slice* (pagination)

**Comment by lorenzofox3** [comment] 2015-02-23 05:18
duplicate of #261

**Closed** 2015-02-23 05:18 UTC

**Comment by visitha** [comment] 2017-11-24 12:14
Hi @lorenzofox3 Thank you very for this great plug-in! It is really awesome

I am trying to add a select all functionality with check boxes for each row using a directive. But when I have several pages, I just want to select all rows of only currently displaying page. Not rows of all pages. How can I select only rows of current displaying page?

Thanks!!
