### ISSUE TITLE
st-search dont works with subproperties

### ISSUE THREAD

**Issue by cgarnier** [lorenzofox3/Smart-Table#344] opened 2015-03-23 16:10 UTC
Hello,
We doesnt alloy to search by subproperties. 
sample:
I go a car list.
{name: "car1",  status:{name: "crashed"}} 
st-search="status.name" doesnt work.

**Comment by cgarnier** [comment] 2015-03-23 16:44
I found a way but i find it s deep so i wont pull request it.

in table controller:
```javascript
    this.search = function search (input, predicate) {
      console.log('DEBUG - predicate: ', predicate);
      var predicateObject = tableState.search.predicateObject || {};
      var prop = predicate ? predicate : '$';

      input = ng.isString(input) ? input.trim() : input;
      var arr = prop.split('.');
      var firstProp = arr[0];
      var obj = predicateObject;
      var obj_1 = predicateObject;
      var p = null;
      while(arr.length){
        p = arr.shift();
        obj_1 = obj;
        obj[p] = {};
        obj = obj[p];
      }
      obj_1[p] = input;
      console.log('DEBUG - pred: ', predicateObject);;

      // to avoid to filter out null value
      if (!input) {
        delete predicateObject[firstProp];
      }
      tableState.search.predicateObject = predicateObject;
      tableState.pagination.start = 0;
      return this.pipe();
    };
```

in stSearch:
```javascript
        scope.$watch(function () {
          return ctrl.tableState().search;
        }, function (newValue, oldValue) {
          if(!newValue.predicateObject) return;
          var predicateExpression = attr.stSearch || '$';
          var arr = predicateExpression.split('.');
          var obj = newValue.predicateObject;
          var obj_1 = newValue.predicateObject;
          var p = null;
          while(arr.length){
            p = arr.shift();
            if(!obj[p]) return;
            obj_1 = obj;
            obj = obj[p];
          }
          obj_1[p];
          if (obj_1[p] && obj_1[p] !== element[0].value) {
            element[0].value = obj_1[p] || '';
          }
        }, true);
```

**Comment by lorenzofox3** [comment] 2015-03-24 02:17
You can use a custom filter if you want: duplicate of https://github.com/lorenzofox3/Smart-Table/issues/184 and https://github.com/lorenzofox3/Smart-Table/issues/288

**Closed by lorenzofox3** 2015-03-24 02:17 UTC
