### ISSUE TITLE
Retrive collection of filtered data

### ISSUE THREAD

**Issue by BobKurtis** [lorenzofox3/Smart-Table#318] opened 2015-03-04 16:17 UTC
Is there a way to retrieve the array of filtered results (regardless of page). i can retrieve the filtered results per page with displayedCollection but is there a filteredCollection or a way to achieve it, I'm exporting smart-table to csv

**Comment by lorenzofox3** [comment] 2015-03-05 02:17
duplicate of https://github.com/lorenzofox3/Smart-Table/issues/261

**Closed by lorenzofox3** 2015-03-05 02:17 UTC

**Comment by ProNJ** [comment] 2015-12-28 06:18
Can you please provide demo or plunker for the same functionality.
